#!/usr/bin/env node
// Reads the 32×32 dither source and emits:
//   - src/app/icon.svg        (standalone favicon)
//   - src/ui/logo-dither.ts   (path data imported by src/ui/logo.tsx)
// No resolution change — the source grid is used directly. Game Boy colors
// are remapped to the lighter end of the mist palette so the mark reads
// against the mist-900 page background.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const SRC = join(ROOT, 'src/app/dither-2026-04-17-z6pxnx.svg');

// Game Boy → mist (light end only, starting at mist-200).
const COLOR_MAP = {
  '#0f380f': 'oklch(.48 .05 260)', // mist-500
  '#306230': 'oklch(.6 .04 250)',  // mist-400
  '#8bac0f': 'oklch(.74 .03 238)', // mist-300
};
const BG_OUT = 'oklch(.86 .02 233)'; // mist-200 (was #9bbc0f)
const GRID = 32;
const CELL = 8;

function parse(svg) {
  const groups = {};
  const groupRe = /<g fill="(#[0-9a-fA-F]+)"[^>]*>([\s\S]*?)<\/g>/g;
  let m;
  while ((m = groupRe.exec(svg)) !== null) {
    const fill = m[1].toLowerCase();
    const rects = [];
    const rectRe = /<rect x="(\d+)" y="(\d+)" width="8" height="8"\/>/g;
    let r;
    while ((r = rectRe.exec(m[2])) !== null) {
      rects.push([+r[1] / CELL, +r[2] / CELL]);
    }
    groups[fill] = rects;
  }
  return groups;
}

// Horizontal run-length + greedy vertical merge.
function rectCover(cells) {
  const grid = new Map();
  for (const [x, y] of cells) {
    if (!grid.has(y)) grid.set(y, new Set());
    grid.get(y).add(x);
  }
  const rowRuns = new Map();
  const ys = [...grid.keys()].sort((a, b) => a - b);
  for (const y of ys) {
    const xs = [...grid.get(y)].sort((a, b) => a - b);
    const runs = [];
    let i = 0;
    while (i < xs.length) {
      let j = i;
      while (j + 1 < xs.length && xs[j + 1] === xs[j] + 1) j++;
      runs.push([xs[i], xs[j] - xs[i] + 1]);
      i = j + 1;
    }
    rowRuns.set(y, runs);
  }
  const used = new Map();
  const out = [];
  for (const y of ys) {
    const runs = rowRuns.get(y);
    for (let ri = 0; ri < runs.length; ri++) {
      if (used.get(y)?.has(ri)) continue;
      const [x, w] = runs[ri];
      let h = 1;
      let yy = y + 1;
      while (rowRuns.has(yy)) {
        const nextRuns = rowRuns.get(yy);
        const idx = nextRuns.findIndex(([nx, nw]) => nx === x && nw === w);
        if (idx === -1) break;
        if (used.get(yy)?.has(idx)) break;
        if (!used.has(yy)) used.set(yy, new Set());
        used.get(yy).add(idx);
        h++;
        yy++;
      }
      out.push([x, y, w, h]);
    }
  }
  return out;
}

function rectsToPath(rects) {
  rects.sort((a, b) => a[1] - b[1] || a[0] - b[0]);
  return rects
    .map(([x, y, w, h]) =>
      w === 1 && h === 1
        ? `M${x} ${y}h1v1h-1`
        : `M${x} ${y}h${w}v${h}h-${w}`,
    )
    .join('');
}

function main() {
  const groups = parse(readFileSync(SRC, 'utf8'));
  const colorData = [];
  for (const [fill, color] of Object.entries(COLOR_MAP)) {
    const cells = groups[fill] || [];
    const rects = rectCover(cells);
    colorData.push({ color, d: rectsToPath(rects) });
    console.log(`  ${fill}: ${cells.length} cells → ${rects.length} rects`);
  }

  const r = GRID / 2;
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${GRID} ${GRID}" shape-rendering="crispEdges">` +
    `<defs><clipPath id="c"><circle cx="${r}" cy="${r}" r="${r}"/></clipPath></defs>` +
    `<g clip-path="url(#c)">` +
    `<path fill="${BG_OUT}" d="M0 0h${GRID}v${GRID}h-${GRID}"/>` +
    colorData.map(({ color, d }) => `<path fill="${color}" d="${d}"/>`).join('') +
    `</g></svg>\n`;

  const iconPath = join(ROOT, 'src/app/icon.svg');
  writeFileSync(iconPath, svg);
  console.log(`wrote ${iconPath} (${(svg.length / 1024).toFixed(1)} KB)`);

  const ts =
    `// Auto-generated by scripts/build-logo.mjs. Do not edit by hand.\n` +
    `export const DITHER_GRID = ${GRID};\n` +
    `export const DITHER_BG = ${JSON.stringify(BG_OUT)};\n` +
    `export const DITHER_PATHS: ReadonlyArray<{ color: string; d: string }> = [\n` +
    colorData
      .map(({ color, d }) => `  { color: ${JSON.stringify(color)}, d: ${JSON.stringify(d)} },`)
      .join('\n') +
    `\n];\n`;
  const tsPath = join(ROOT, 'src/ui/logo-dither.ts');
  mkdirSync(dirname(tsPath), { recursive: true });
  writeFileSync(tsPath, ts);
  console.log(`wrote ${tsPath} (${(ts.length / 1024).toFixed(1)} KB)`);
}

main();
